/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kevin_jni_JavaCallC */

#ifndef _Included_com_kevin_jni_JavaCallC
#define _Included_com_kevin_jni_JavaCallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kevin_jni_JavaCallC
 * Method:    callC
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kevin_jni_JavaCallC_callC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
